services:
  proxy:
    build: ./proxy
    container_name: school-secretary-proxy
    ports:
      - "8080:80"
    depends_on:
      - api
      - app
    networks:
      - public
    volumes:
      - static_volume:/vol/web/static/
      - media_volume:/vol/web/media/

  app:
    build: ./app
    image: webcorvus/school-secretary-app:latest
    container_name: school-secretary-app
    command: sh -c "npm run start"
    env_file:
      - .env.base
      - .env.prod
      - .env.local
    depends_on:
      - api
    develop:
      watch:
        - action: rebuild
          path: ./app
          target: /app
    networks:
      - public
    restart: unless-stopped

  api:
    build: ./api
    image: webcorvus/school-secretary-api:latest
    container_name: school-secretary-api
    command: sh -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && gunicorn School-Secretary.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - db_data:/api/data
      - static_volume:/vol/web/static/
      - media_volume:/vol/web/media/
    env_file:
      - .env.base
      - .env.prod
      - .env.local
    depends_on:
      - db
    networks:
      - public
      - private
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: school-secretary-db
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env.base
      - .env.prod
      - .env.local
    networks:
      - private
    restart: unless-stopped

networks:
  public:
    driver: bridge
  private:
    driver: bridge

volumes:
  db_data:
  static_volume:
  media_volume:
